version: "3"

services:
  mysql:
    image: mysql:8.0.0
    container_name: goms-mysql
    platform: linux/amd64  
  
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: rudtnrud21608!
      MYSQL_USER: kim
      MYSQL_PASSWORD: rudtn1991!
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: goms-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  go:
    build:
      context: .
      dockerfile: Dockerfile
    image: kimgyeongsu/goms-go
    container_name: goms-go
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data: