jwt:
  access_secret: ${ACCESS_SECRET}
  refresh_secret: ${REFRESH_SECRET}
  access_exp: ${ACCESS_EXP}
  refresh_exp: ${REFRESH_EXP}

outing:
  outing_exp: ${OUTING_EXP}
  outing_blacklist_exp: ${OUTING_BLACK_EXP}

data:
  mysql:  
    user: ${MYSQL_USER}
    pass: ${MYSQL_PASSWORD}
    host: ${MYSQL_HOST}
    port: ${MYSQL_PORT}
    db: ${MYSQL_NAME}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  mongo:  
    user: ${MONGO_USER}
    pass: ${MONGO_PASSWORD}
    host: ${MONGO_HOST}
    port: ${MONGO_PORT}
    db: ${MONGO_NAME}

email:
  id: ${EMAIL_ID}
  pass: ${EMAIL_PASSWORD}