definitions:
  constant.Authority:
    enum:
    - ROLE_STUDENT
    - ROLE_STUDENT_COUNCIL
    type: string
    x-enum-varnames:
    - ROLE_STUDENT
    - ROLE_STUDENT_COUNCIL
  input.SignInInput:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  input.SignUpInput:
    properties:
      email:
        type: string
      gender:
        type: string
      major:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  output.TokenOutput:
    properties:
      accessToken:
        type: string
      accessTokenExp:
        type: string
      authority:
        $ref: '#/definitions/constant.Authority'
      refreshToken:
        type: string
      refreshTokenExp:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/auth:
    patch:
      consumes:
      - application/json
      description: RefreshToken를 header로 받아서 요청.
      parameters:
      - description: Refresh Token
        in: header
        name: RefreshToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 토큰 재발급 성공
          schema:
            $ref: '#/definitions/output.TokenOutput'
      summary: 토큰 재발급 Router
  /api/v1/auth/signin:
    post:
      consumes:
      - application/json
      description: email과 password를 통해 로그인 후 토큰 발급.
      parameters:
      - description: User login credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/input.SignInInput'
      produces:
      - application/json
      responses:
        "200":
          description: 로그인 성공
          schema:
            $ref: '#/definitions/output.TokenOutput'
      summary: 로그인 Router
  /api/v1/auth/signup:
    post:
      consumes:
      - application/json
      description: email인증 후 학과 정보를 통해 사용자 회원가입.
      parameters:
      - description: User information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/input.SignUpInput'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            type: string
      summary: 회원가입 Router
swagger: "2.0"
